name: Build App on PR Label

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'build-app') ||
      contains(github.event.pull_request.labels.*.name, 'build-apk-release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        if: contains(github.event.pull_request.labels.*.name, 'build-app')
        run: ./gradlew assembleDebug

      - name: Upload Debug APK Artifact
        if: contains(github.event.pull_request.labels.*.name, 'build-app')
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        if: contains(github.event.pull_request.labels.*.name, 'build-apk-release')
        run: ./gradlew assembleRelease

      - name: Upload Release APK Artifact
        if: contains(github.event.pull_request.labels.*.name, 'build-apk-release')
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
